{% set name = "pyvkfft" %}
{% set version = "2022.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyvkfft-{{ version }}.tar.gz
  sha256: d283542c14e5a0fac15d91018b8390dce397b3e02fc9c43a16cd799886801d45
  patches:
    - conda_libraries.diff
    - ccbin.diff

build:
  number: 2
  entry_points:
    - pyvkfft-test = pyvkfft.scripts.pyvkfft_test:main
  script:
    - set "CC="    # [win]
    - set "CXX="   # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
  host:
    - pip
    - python
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [win or osx]
  run:
    - numpy
    - psutil
    - pyopencl
    - python
    - __cuda =={{ cuda_compiler_version }}  # [cuda_compiler_version in ('10.2', '11.0', '11.1')]
    - __cuda >={{ cuda_compiler_version }},<12  # [cuda_compiler_version == '11.2']
  run_constrained:
    - cudatoolkit =={{ cuda_compiler_version }}  # [cuda_compiler_version in ('10.2', '11.0', '11.1')]
    - cudatoolkit >={{ cuda_compiler_version }},<12  # [cuda_compiler_version == '11.2']

test:
  imports:
    - pyvkfft
  commands:
    - pyvkfft-test --help

about:
  home: https://github.com/vincefn/pyvkfft
  summary: Python wrapper for the CUDA and OpenCL backends of VkFFT, providing GPU FFT for PyCUDA, PyOpenCL and CuPy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
