{% set name = "pyvkfft" %}
{% set version = "2023.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyvkfft-{{ version }}.tar.gz
  sha256: 090132fa3e94d88dbda5cf4585f83b1c98a45850d64f34652b7e80e86145893b
  patches:
    - conda_libraries.diff

build:
  number: 0
  entry_points:
    - pyvkfft-test = pyvkfft.scripts.pyvkfft_test:main
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
  host:
    - cuda-nvrtc-dev      # [(cuda_compiler_version or "").startswith("12")]
    - pip
    - python
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [win or osx]
    - ocl_icd_wrapper_apple  # [osx]
  run:
    - numpy
    - psutil
    - pyopencl
    - python
    - __cuda =={{ cuda_compiler_version }}  # [cuda_compiler_version in ('10.2', '11.0', '11.1')]
    - __cuda >={{ cuda_compiler_version }},<12  # [cuda_compiler_version == '11.2']
  run_constrained:
    - cudatoolkit =={{ cuda_compiler_version }}  # [cuda_compiler_version in ('10.2', '11.0', '11.1')]
    - cudatoolkit >={{ cuda_compiler_version }},<12  # [cuda_compiler_version == '11.2']

test:
  imports:
    - pyvkfft
#  commands:
#    - pyvkfft-test --help

about:
  home: https://github.com/vincefn/pyvkfft
  summary: Python wrapper for the CUDA and OpenCL backends of VkFFT, providing GPU FFT for PyCUDA, PyOpenCL and CuPy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vincefn
    - isuruf
