{% set name = "pyvkfft" %}
{% set version = "2024.1.4" %}
{% if cuda_compiler_version is undefined %}
{% set cuda_compiler_version = "None" %}
{% endif %}
{% set cuda_major = 0 if cuda_compiler_version == "None" else cuda_compiler_version|int %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyvkfft-{{ version }}.tar.gz
  sha256: feaf3dcc9b2f2ea556ff8b6d1157520d3faa8ba8326c694d4136c974f13ee191
  patches:
    - conda_libraries.diff

build:
  number: 1
  entry_points:
    - pyvkfft-test = pyvkfft.scripts.pyvkfft_test:main
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  ignore_run_exports_from:
    - {{ compiler('cuda') }}

# TODO: why is gxx needed in addition of compiler{cxx} ? Otherwise nvcc fails with 'gcc: no such file..' ?
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - gxx                                    # [linux]
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - setuptools
  host:
    - pip
    - python
    - ocl-icd-system                        # [linux]
    - khronos-opencl-icd-loader             # [win or osx]
    - ocl_icd_wrapper_apple                 # [osx]
    - cuda-version >={{ cuda_compiler_version }},<{{ cuda_major + 1 }}.0a0  # [cuda_compiler_version != "None"]
    - cuda-nvrtc-dev                         # [(cuda_compiler_version or "").startswith("12")]
  run:
    - numpy
    - psutil
    - pyopencl
    - python
    - __cuda >={{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - cuda-nvrtc                            # [(cuda_compiler_version or "").startswith("12")]
    - cudatoolkit                           # [(cuda_compiler_version or "").startswith("11")]
  run_constrained:
    - __cuda <0.0a0                         # [cuda_compiler_version == "None"]

test:
  imports:
    - pyvkfft
    - pyvkfft.base
    - pyvkfft.test._test_opencl_lib
    - pyvkfft.test._test_cuda_lib           # [cuda_compiler_version != "None"]
#  commands:
#    - pyvkfft-test --help

about:
  home: https://github.com/vincefn/pyvkfft
  summary: Python wrapper for the CUDA and OpenCL backends of VkFFT, providing GPU FFT for PyCUDA, PyOpenCL and CuPy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vincefn
    - isuruf
